@extends('layouts.app')
 10
@section('content')
 <divclass="container">
    <divclass="rowjustify-content-center">
        <divclass="col-md-8">
            <divclass="card">
                <divclass="card-header">{{__('Dashboard')}}</div>
                    <divclass="card-body">
                        @if(session('status'))
                            <divclass="alertalert-success"role="alert">
                                {{session('status')}}
                            </div>
                        @endif
                        You are a Mahasiswa.
                    </div>
                </div>
            </div>
        </div>
    </div>
 @endsection